### ISSUE TITLE
Can't wait to order a Chat64 kit!!!

### ISSUE THREAD

**Issue by Paulie420** [bvenneker/Chat64#1]
Thru-Hole, of course. - let us know where we can go.....

**Comment by SvenPook** [comment]
An issue has been found, making the cartridges incompatible with some Commodore 64 board revisions. We want to fix this first to make sure every cartridge will work fine with any revision mainboard. Please bear with us, a new revision will be available soon.

**Comment by SvenPook** [comment]
see comment above

**Comment by bvenneker** [comment]
See: https://www.etsy.com/shop/bartselektronica
