### ISSUE TITLE
SSID names with spacebars not working

### ISSUE THREAD

**Issue by dimian123** [bvenneker/Chat64#15]
I have trouble connecting to wifi. I have spacebars in my SSID name (for example "ASUS Wifi").
When I type in on the C64 it gives me error and the SSID name only displays the first word.
It works when I connect to my mobile hotspot SSID named "test".

**Comment by bvenneker** [comment]
Hi, Yes that is a known limitation at the moment. We will change that in the future?

for my information: What version number do you see at the bottom of the main menu?

**Comment by dimian123** [comment]
Version is ROM 3.64 ESP 3.68 04/2024

**Comment by bvenneker** [comment]
I will fix that issue with spaces in the SSID name this weekend.
Do you have experience with the Arduino IDE?  are you able to upload new firmware to the ESP32?

**Comment by dimian123** [comment]
Ok, cool!
Yes I have everything setup and ready.

**Comment by bvenneker** [comment]
Okay, 
You will need to download this zip file
https://github.com/bvenneker/Chat64/blob/Boot-Loader/ESP32%20Sketch/C64_Chat_3_71.zip
and follow the steps in this readme 
https://github.com/bvenneker/Chat64/blob/Boot-Loader/ESP32%20Sketch/C64_Chat_3_71/readme.md

**Comment by dimian123** [comment]
working!

**Comment by bvenneker** [comment]
Nice, Closing issue
